branches:
  only:
    - master
    
environment:
  access_token:
    secure: jf56pSYTaUx5sBJCVt2IDCzmPrZ2iOTYrSVvCzEt17UhGKq3RfqlO4aIZ3bRlZSX

install:
  - mkdir ..\Wyam
  - mkdir ..\Output
  - "curl -s https://api.github.com/repos/Wyamio/wyam/releases | grep tag_name | head -n 1 | grep -oP ': \"\\K[^\"]*' > wyamversion.txt"
  - set /P WYAMVERSION=< wyamversion.txt
  - ps: Start-FileDownload https://github.com/Wyamio/Wyam/releases/download/%WYAMVERSION%/Wyam.zip -FileName "..\Wyam\Wyam.zip"
  - 7z x ..\Wyam\Wyam.zip -o..\Wyam -r

build_script:
  - ..\Wyam\Wyam.exe --output ..\Output

on_success:
  # http://www.appveyor.com/docs/how-to/git-push
  - git config --global credential.helper store
  - git config --global user.email "dave@daveaglick.com"
  - git config --global user.name "Dave Glick"
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git checkout gh-pages
  - git rm -rf .
  - xcopy ..\Output . /E
  - echo wyam.io > CNAME
  - git remote set-url origin https://github.com/Wyamio/Wyam.Web.git
  - git add -A
  - git commit -a -m "Commit from AppVeyor"
  - git push
